/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 -T chair-1.glb
Files: chair-1.glb [5.61MB] > chair-1-transformed.glb [1.34MB] (76%)
*/

import React, { useRef } from 'react'
import { useGLTF, Html, PresentationControls } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Chair(props) {
  const { nodes, materials } = useGLTF('../../../models/chair-1-transformed.glb')
  const chairRef = useRef()

  // useFrame(({ clock }) => {
  //   chairRef.current.rotation.y = clock.getElapsedTime() / 2
  // })
  return (
    <>

    <group {...props} dispose={null} ref={chairRef}>
      <PresentationControls
      speed={4}
      polar={[0, 0]}
      >
      <mesh geometry={nodes.Chair_Fabric_Parts.geometry} material={materials.Fabric} position={[-0.055, 0.544, -0.002]} />
      <mesh geometry={nodes.Chair_Wood_Parts_1.geometry} material={materials.Wood} position={[0.033, 0.413, -0.001]} />
      <Html>
        <h3>Category</h3>
      </Html>

      </PresentationControls>
    </group>

    </>
  )
}

useGLTF.preload('../../../models/chair-1-transformed.glb')
