/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 -T showroom.glb
Files: showroom.glb [792.2KB] > showroom-transformed.glb [772.68KB] (2%)
*/

import React, { useRef } from 'react'
import { useGLTFLoader, PerspectiveCamera, Gltf } from '@react-three/drei'

export function Model(props) {
  return (
    <Gltf src='../../../models/scene.gltf'/>
  )
}
